// Generated by scripts/update-data.mjs.
export const SNAPSHOT = {
  "fetchedAt": "2026-06-20T01:55:54.370Z",
  "source": "https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard?limit=200&dates=20260611-20260719",
  "teams": [
    {
      "id": "624",
      "name": "Algeria",
      "abbreviation": "ALG",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/alg.png",
      "color": "4F9A44",
      "isPlaceholder": false
    },
    {
      "id": "202",
      "name": "Argentina",
      "abbreviation": "ARG",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/arg.png",
      "color": "74acdf",
      "isPlaceholder": false
    },
    {
      "id": "628",
      "name": "Australia",
      "abbreviation": "AUS",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/aus.png",
      "color": "FFCD00",
      "isPlaceholder": false
    },
    {
      "id": "474",
      "name": "Austria",
      "abbreviation": "AUT",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/aut.png",
      "color": "d72b2c",
      "isPlaceholder": false
    },
    {
      "id": "459",
      "name": "Belgium",
      "abbreviation": "BEL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/bel.png",
      "color": "E30613",
      "isPlaceholder": false
    },
    {
      "id": "452",
      "name": "Bosnia-Herzegovina",
      "abbreviation": "BIH",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/bih.png",
      "color": "112855",
      "isPlaceholder": false
    },
    {
      "id": "205",
      "name": "Brazil",
      "abbreviation": "BRA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
      "color": "fee000",
      "isPlaceholder": false
    },
    {
      "id": "206",
      "name": "Canada",
      "abbreviation": "CAN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/can.png",
      "color": "ed2224",
      "isPlaceholder": false
    },
    {
      "id": "2597",
      "name": "Cape Verde",
      "abbreviation": "CPV",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/cpv.png",
      "color": "000080",
      "isPlaceholder": false
    },
    {
      "id": "208",
      "name": "Colombia",
      "abbreviation": "COL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/col.png",
      "color": "fbd632",
      "isPlaceholder": false
    },
    {
      "id": "2850",
      "name": "Congo DR",
      "abbreviation": "COD",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/rdc.png",
      "color": "418fde",
      "isPlaceholder": false
    },
    {
      "id": "477",
      "name": "Croatia",
      "abbreviation": "CRO",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/cro.png",
      "color": "ff0000",
      "isPlaceholder": false
    },
    {
      "id": "11678",
      "name": "Curaçao",
      "abbreviation": "CUW",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/soccer/500/11678.png",
      "color": "0537e4",
      "isPlaceholder": false
    },
    {
      "id": "450",
      "name": "Czechia",
      "abbreviation": "CZE",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/cze.png",
      "color": "d7141a",
      "isPlaceholder": false
    },
    {
      "id": "209",
      "name": "Ecuador",
      "abbreviation": "ECU",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/ecu.png",
      "color": "ffdd00",
      "isPlaceholder": false
    },
    {
      "id": "2620",
      "name": "Egypt",
      "abbreviation": "EGY",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/egy.png",
      "color": "D20300",
      "isPlaceholder": false
    },
    {
      "id": "448",
      "name": "England",
      "abbreviation": "ENG",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/eng.png",
      "color": "ffffff",
      "isPlaceholder": false
    },
    {
      "id": "478",
      "name": "France",
      "abbreviation": "FRA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/fra.png",
      "color": "000080",
      "isPlaceholder": false
    },
    {
      "id": "481",
      "name": "Germany",
      "abbreviation": "GER",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/ger.png",
      "color": "FFFFFF",
      "isPlaceholder": false
    },
    {
      "id": "4469",
      "name": "Ghana",
      "abbreviation": "GHA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/gha.png",
      "color": "fbd632",
      "isPlaceholder": false
    },
    {
      "id": "5926",
      "name": "Group A 2nd Place",
      "abbreviation": "2A",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5924",
      "name": "Group B 2nd Place",
      "abbreviation": "2B",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5925",
      "name": "Group B Winner",
      "abbreviation": "1B",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5930",
      "name": "Group C 2nd Place",
      "abbreviation": "2C",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5927",
      "name": "Group C Winner",
      "abbreviation": "1C",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5928",
      "name": "Group D 2nd Place",
      "abbreviation": "2D",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5929",
      "name": "Group D Winner",
      "abbreviation": "1D",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5932",
      "name": "Group E 2nd Place",
      "abbreviation": "2E",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5931",
      "name": "Group E Winner",
      "abbreviation": "1E",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5934",
      "name": "Group F 2nd Place",
      "abbreviation": "2F",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5933",
      "name": "Group F Winner",
      "abbreviation": "1F",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5936",
      "name": "Group G 2nd Place",
      "abbreviation": "2G",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5935",
      "name": "Group G Winner",
      "abbreviation": "1G",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5938",
      "name": "Group H 2nd Place",
      "abbreviation": "2H",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5937",
      "name": "Group H Winner",
      "abbreviation": "1H",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131501",
      "name": "Group I 2nd Place",
      "abbreviation": "2I",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131505",
      "name": "Group I Winner",
      "abbreviation": "1I",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131502",
      "name": "Group J 2nd Place",
      "abbreviation": "2J",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131506",
      "name": "Group J Winner",
      "abbreviation": "1J",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131503",
      "name": "Group K 2nd Place",
      "abbreviation": "2K",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131507",
      "name": "Group K Winner",
      "abbreviation": "1K",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131504",
      "name": "Group L 2nd Place",
      "abbreviation": "2L",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131508",
      "name": "Group L Winner",
      "abbreviation": "1L",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "2654",
      "name": "Haiti",
      "abbreviation": "HAI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/hai.png",
      "color": "0033a0",
      "isPlaceholder": false
    },
    {
      "id": "469",
      "name": "Iran",
      "abbreviation": "IRN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/irn.png",
      "color": "FFFFFF",
      "isPlaceholder": false
    },
    {
      "id": "4375",
      "name": "Iraq",
      "abbreviation": "IRQ",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/irq.png",
      "color": "0A4D2E",
      "isPlaceholder": false
    },
    {
      "id": "4789",
      "name": "Ivory Coast",
      "abbreviation": "CIV",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/civ.png",
      "color": "FF8200",
      "isPlaceholder": false
    },
    {
      "id": "627",
      "name": "Japan",
      "abbreviation": "JPN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/jpn.png",
      "color": "000555",
      "isPlaceholder": false
    },
    {
      "id": "2917",
      "name": "Jordan",
      "abbreviation": "JOR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/jor.png",
      "color": "E70000",
      "isPlaceholder": false
    },
    {
      "id": "203",
      "name": "Mexico",
      "abbreviation": "MEX",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/mex.png",
      "color": "006847",
      "isPlaceholder": false
    },
    {
      "id": "2869",
      "name": "Morocco",
      "abbreviation": "MAR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/mar.png",
      "color": "df2027",
      "isPlaceholder": false
    },
    {
      "id": "449",
      "name": "Netherlands",
      "abbreviation": "NED",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/ned.png",
      "color": "fb5d00",
      "isPlaceholder": false
    },
    {
      "id": "2666",
      "name": "New Zealand",
      "abbreviation": "NZL",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/nzl.png",
      "color": "000000",
      "isPlaceholder": false
    },
    {
      "id": "464",
      "name": "Norway",
      "abbreviation": "NOR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/nor.png",
      "color": "C8102E",
      "isPlaceholder": false
    },
    {
      "id": "2659",
      "name": "Panama",
      "abbreviation": "PAN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/pan.png",
      "color": "d21034",
      "isPlaceholder": false
    },
    {
      "id": "210",
      "name": "Paraguay",
      "abbreviation": "PAR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/par.png",
      "color": "ea2300",
      "isPlaceholder": false
    },
    {
      "id": "482",
      "name": "Portugal",
      "abbreviation": "POR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/por.png",
      "color": "da291c",
      "isPlaceholder": false
    },
    {
      "id": "4398",
      "name": "Qatar",
      "abbreviation": "QAT",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/qat.png",
      "color": "691a40",
      "isPlaceholder": false
    },
    {
      "id": "17631",
      "name": "Quarterfinal 1 Winner",
      "abbreviation": "QFW1",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "17629",
      "name": "Quarterfinal 2 Winner",
      "abbreviation": "QFW2",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "17630",
      "name": "Quarterfinal 3 Winner",
      "abbreviation": "QFW3",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "17632",
      "name": "Quarterfinal 4 Winner",
      "abbreviation": "QW4",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "19282",
      "name": "Round of 16 1 Winner",
      "abbreviation": "RD16 W1",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "19283",
      "name": "Round of 16 2 Winner",
      "abbreviation": "RD16 W2",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "19284",
      "name": "Round of 16 3 Winner",
      "abbreviation": "RD16 W3",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "19285",
      "name": "Round of 16 4 Winner",
      "abbreviation": "RD16 W4",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "19278",
      "name": "Round of 16 5 Winner",
      "abbreviation": "RD16 W5",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "19279",
      "name": "Round of 16 6 Winner",
      "abbreviation": "RD16 W6",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "19280",
      "name": "Round of 16 7 Winner",
      "abbreviation": "RD16 W7",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "19281",
      "name": "Round of 16 8 Winner",
      "abbreviation": "RD16 W8",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131525",
      "name": "Round of 32 1 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131534",
      "name": "Round of 32 10 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131535",
      "name": "Round of 32 11 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131536",
      "name": "Round of 32 12 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131537",
      "name": "Round of 32 13 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131538",
      "name": "Round of 32 14 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131539",
      "name": "Round of 32 15 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131540",
      "name": "Round of 32 16 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131526",
      "name": "Round of 32 2 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131527",
      "name": "Round of 32 3 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131528",
      "name": "Round of 32 4 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131529",
      "name": "Round of 32 5 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131530",
      "name": "Round of 32 6 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131531",
      "name": "Round of 32 7 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131532",
      "name": "Round of 32 8 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131533",
      "name": "Round of 32 9 Winner",
      "abbreviation": "RD32",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "655",
      "name": "Saudi Arabia",
      "abbreviation": "KSA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/ksa.png",
      "color": "FFFFFF",
      "isPlaceholder": false
    },
    {
      "id": "580",
      "name": "Scotland",
      "abbreviation": "SCO",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/sco.png",
      "color": "1a2d69",
      "isPlaceholder": false
    },
    {
      "id": "5958",
      "name": "Semifinal 1 Loser",
      "abbreviation": "SF L1",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5960",
      "name": "Semifinal 1 Winner",
      "abbreviation": "SFW1",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5959",
      "name": "Semifinal 2 Loser",
      "abbreviation": "SF L2",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "5961",
      "name": "Semifinal 2 Winner",
      "abbreviation": "SFW2",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "654",
      "name": "Senegal",
      "abbreviation": "SEN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/sen.png",
      "color": "006436",
      "isPlaceholder": false
    },
    {
      "id": "467",
      "name": "South Africa",
      "abbreviation": "RSA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/rsa.png",
      "color": "FFB81C",
      "isPlaceholder": false
    },
    {
      "id": "451",
      "name": "South Korea",
      "abbreviation": "KOR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/kors.png",
      "color": "ce2028",
      "isPlaceholder": false
    },
    {
      "id": "164",
      "name": "Spain",
      "abbreviation": "ESP",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/esp.png",
      "color": "c60b1e",
      "isPlaceholder": false
    },
    {
      "id": "466",
      "name": "Sweden",
      "abbreviation": "SWE",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/swe.png",
      "color": "fecb00",
      "isPlaceholder": false
    },
    {
      "id": "475",
      "name": "Switzerland",
      "abbreviation": "SUI",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/sui.png",
      "color": "FF0000",
      "isPlaceholder": false
    },
    {
      "id": "131541",
      "name": "Third Place Group A/B/C/D/F",
      "abbreviation": "3RD",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131542",
      "name": "Third Place Group A/E/H/I/J",
      "abbreviation": "3RD",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131543",
      "name": "Third Place Group B/E/F/I/J",
      "abbreviation": "3RD",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131544",
      "name": "Third Place Group C/D/F/G/H",
      "abbreviation": "3RD",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131545",
      "name": "Third Place Group C/E/F/H/I",
      "abbreviation": "3RD",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131546",
      "name": "Third Place Group D/E/I/J/L",
      "abbreviation": "3RD",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131547",
      "name": "Third Place Group E/F/G/I/J",
      "abbreviation": "3RD",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "131548",
      "name": "Third Place Group E/H/I/J/K",
      "abbreviation": "3RD",
      "logoUrl": "",
      "color": "000000",
      "isPlaceholder": true
    },
    {
      "id": "659",
      "name": "Tunisia",
      "abbreviation": "TUN",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/tun.png",
      "color": "D20300",
      "isPlaceholder": false
    },
    {
      "id": "465",
      "name": "Türkiye",
      "abbreviation": "TUR",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/tur.png",
      "color": "ffffff",
      "isPlaceholder": false
    },
    {
      "id": "660",
      "name": "United States",
      "abbreviation": "USA",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
      "color": "d42339",
      "isPlaceholder": false
    },
    {
      "id": "212",
      "name": "Uruguay",
      "abbreviation": "URU",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/uru.png",
      "color": "55B5E5",
      "isPlaceholder": false
    },
    {
      "id": "2570",
      "name": "Uzbekistan",
      "abbreviation": "UZB",
      "logoUrl": "https://a.espncdn.com/i/teamlogos/countries/500/uzb.png",
      "color": "ffffff",
      "isPlaceholder": false
    }
  ],
  "matches": [
    {
      "id": "760415",
      "phase": "group-stage",
      "group": "A",
      "kickoffUtc": "2026-06-11T19:00Z",
      "venue": "Estadio Banorte",
      "homeTeamId": "203",
      "awayTeamId": "467",
      "apiScore": {
        "home": 2,
        "away": 0
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "203"
    },
    {
      "id": "760414",
      "phase": "group-stage",
      "group": "A",
      "kickoffUtc": "2026-06-12T02:00Z",
      "venue": "Estadio Akron",
      "homeTeamId": "451",
      "awayTeamId": "450",
      "apiScore": {
        "home": 2,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "451"
    },
    {
      "id": "760416",
      "phase": "group-stage",
      "group": "B",
      "kickoffUtc": "2026-06-12T19:00Z",
      "venue": "BMO Field",
      "homeTeamId": "206",
      "awayTeamId": "452",
      "apiScore": {
        "home": 1,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true
    },
    {
      "id": "760417",
      "phase": "group-stage",
      "group": "D",
      "kickoffUtc": "2026-06-13T01:00Z",
      "venue": "SoFi Stadium",
      "homeTeamId": "660",
      "awayTeamId": "210",
      "apiScore": {
        "home": 4,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "660"
    },
    {
      "id": "760420",
      "phase": "group-stage",
      "group": "B",
      "kickoffUtc": "2026-06-13T19:00Z",
      "venue": "Levi's Stadium",
      "homeTeamId": "4398",
      "awayTeamId": "475",
      "apiScore": {
        "home": 1,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true
    },
    {
      "id": "760419",
      "phase": "group-stage",
      "group": "C",
      "kickoffUtc": "2026-06-13T22:00Z",
      "venue": "MetLife Stadium",
      "homeTeamId": "205",
      "awayTeamId": "2869",
      "apiScore": {
        "home": 1,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true
    },
    {
      "id": "760418",
      "phase": "group-stage",
      "group": "C",
      "kickoffUtc": "2026-06-14T01:00Z",
      "venue": "Gillette Stadium",
      "homeTeamId": "2654",
      "awayTeamId": "580",
      "apiScore": {
        "home": 0,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "580"
    },
    {
      "id": "760421",
      "phase": "group-stage",
      "group": "D",
      "kickoffUtc": "2026-06-14T04:00Z",
      "venue": "BC Place",
      "homeTeamId": "628",
      "awayTeamId": "465",
      "apiScore": {
        "home": 2,
        "away": 0
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "628"
    },
    {
      "id": "760422",
      "phase": "group-stage",
      "group": "E",
      "kickoffUtc": "2026-06-14T17:00Z",
      "venue": "NRG Stadium",
      "homeTeamId": "481",
      "awayTeamId": "11678",
      "apiScore": {
        "home": 7,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "481"
    },
    {
      "id": "760425",
      "phase": "group-stage",
      "group": "F",
      "kickoffUtc": "2026-06-14T20:00Z",
      "venue": "AT&T Stadium",
      "homeTeamId": "449",
      "awayTeamId": "627",
      "apiScore": {
        "home": 2,
        "away": 2
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true
    },
    {
      "id": "760423",
      "phase": "group-stage",
      "group": "E",
      "kickoffUtc": "2026-06-14T23:00Z",
      "venue": "Lincoln Financial Field",
      "homeTeamId": "4789",
      "awayTeamId": "209",
      "apiScore": {
        "home": 1,
        "away": 0
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "4789"
    },
    {
      "id": "760424",
      "phase": "group-stage",
      "group": "F",
      "kickoffUtc": "2026-06-15T02:00Z",
      "venue": "Estadio BBVA",
      "homeTeamId": "466",
      "awayTeamId": "659",
      "apiScore": {
        "home": 5,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "466"
    },
    {
      "id": "760428",
      "phase": "group-stage",
      "group": "H",
      "kickoffUtc": "2026-06-15T16:00Z",
      "venue": "Mercedes-Benz Stadium",
      "homeTeamId": "164",
      "awayTeamId": "2597",
      "apiScore": {
        "home": 0,
        "away": 0
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true
    },
    {
      "id": "760426",
      "phase": "group-stage",
      "group": "G",
      "kickoffUtc": "2026-06-15T19:00Z",
      "venue": "Lumen Field",
      "homeTeamId": "459",
      "awayTeamId": "2620",
      "apiScore": {
        "home": 1,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true
    },
    {
      "id": "760429",
      "phase": "group-stage",
      "group": "H",
      "kickoffUtc": "2026-06-15T22:00Z",
      "venue": "Hard Rock Stadium",
      "homeTeamId": "655",
      "awayTeamId": "212",
      "apiScore": {
        "home": 1,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true
    },
    {
      "id": "760427",
      "phase": "group-stage",
      "group": "G",
      "kickoffUtc": "2026-06-16T01:00Z",
      "venue": "SoFi Stadium",
      "homeTeamId": "469",
      "awayTeamId": "2666",
      "apiScore": {
        "home": 2,
        "away": 2
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true
    },
    {
      "id": "760432",
      "phase": "group-stage",
      "group": "I",
      "kickoffUtc": "2026-06-16T19:00Z",
      "venue": "MetLife Stadium",
      "homeTeamId": "478",
      "awayTeamId": "654",
      "apiScore": {
        "home": 3,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "478"
    },
    {
      "id": "760430",
      "phase": "group-stage",
      "group": "I",
      "kickoffUtc": "2026-06-16T22:00Z",
      "venue": "Gillette Stadium",
      "homeTeamId": "4375",
      "awayTeamId": "464",
      "apiScore": {
        "home": 1,
        "away": 4
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "464"
    },
    {
      "id": "760433",
      "phase": "group-stage",
      "group": "J",
      "kickoffUtc": "2026-06-17T01:00Z",
      "venue": "GEHA Field at Arrowhead Stadium",
      "homeTeamId": "202",
      "awayTeamId": "624",
      "apiScore": {
        "home": 3,
        "away": 0
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "202"
    },
    {
      "id": "760431",
      "phase": "group-stage",
      "group": "J",
      "kickoffUtc": "2026-06-17T04:00Z",
      "venue": "Levi's Stadium",
      "homeTeamId": "474",
      "awayTeamId": "2917",
      "apiScore": {
        "home": 3,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "474"
    },
    {
      "id": "760435",
      "phase": "group-stage",
      "group": "K",
      "kickoffUtc": "2026-06-17T17:00Z",
      "venue": "NRG Stadium",
      "homeTeamId": "482",
      "awayTeamId": "2850",
      "apiScore": {
        "home": 1,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true
    },
    {
      "id": "760437",
      "phase": "group-stage",
      "group": "L",
      "kickoffUtc": "2026-06-17T20:00Z",
      "venue": "AT&T Stadium",
      "homeTeamId": "448",
      "awayTeamId": "477",
      "apiScore": {
        "home": 4,
        "away": 2
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "448"
    },
    {
      "id": "760434",
      "phase": "group-stage",
      "group": "L",
      "kickoffUtc": "2026-06-17T23:00Z",
      "venue": "BMO Field",
      "homeTeamId": "4469",
      "awayTeamId": "2659",
      "apiScore": {
        "home": 1,
        "away": 0
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "4469"
    },
    {
      "id": "760436",
      "phase": "group-stage",
      "group": "K",
      "kickoffUtc": "2026-06-18T02:00Z",
      "venue": "Estadio Banorte",
      "homeTeamId": "2570",
      "awayTeamId": "208",
      "apiScore": {
        "home": 1,
        "away": 3
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "208"
    },
    {
      "id": "760438",
      "phase": "group-stage",
      "group": "A",
      "kickoffUtc": "2026-06-18T16:00Z",
      "venue": "Mercedes-Benz Stadium",
      "homeTeamId": "450",
      "awayTeamId": "467",
      "apiScore": {
        "home": 1,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true
    },
    {
      "id": "760439",
      "phase": "group-stage",
      "group": "B",
      "kickoffUtc": "2026-06-18T19:00Z",
      "venue": "SoFi Stadium",
      "homeTeamId": "475",
      "awayTeamId": "452",
      "apiScore": {
        "home": 4,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "475"
    },
    {
      "id": "760440",
      "phase": "group-stage",
      "group": "B",
      "kickoffUtc": "2026-06-18T22:00Z",
      "venue": "BC Place",
      "homeTeamId": "206",
      "awayTeamId": "4398",
      "apiScore": {
        "home": 6,
        "away": 0
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "206"
    },
    {
      "id": "760441",
      "phase": "group-stage",
      "group": "A",
      "kickoffUtc": "2026-06-19T01:00Z",
      "venue": "Estadio Akron",
      "homeTeamId": "203",
      "awayTeamId": "451",
      "apiScore": {
        "home": 1,
        "away": 0
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "203"
    },
    {
      "id": "760442",
      "phase": "group-stage",
      "group": "D",
      "kickoffUtc": "2026-06-19T19:00Z",
      "venue": "Lumen Field",
      "homeTeamId": "660",
      "awayTeamId": "628",
      "apiScore": {
        "home": 2,
        "away": 0
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "660"
    },
    {
      "id": "760445",
      "phase": "group-stage",
      "group": "C",
      "kickoffUtc": "2026-06-19T22:00Z",
      "venue": "Gillette Stadium",
      "homeTeamId": "580",
      "awayTeamId": "2869",
      "apiScore": {
        "home": 0,
        "away": 1
      },
      "status": "Full Time",
      "statusDetail": "FT",
      "completed": true,
      "winnerTeamId": "2869"
    },
    {
      "id": "760444",
      "phase": "group-stage",
      "group": "C",
      "kickoffUtc": "2026-06-20T00:30Z",
      "venue": "Lincoln Financial Field",
      "homeTeamId": "205",
      "awayTeamId": "2654",
      "apiScore": {
        "home": 2,
        "away": 0
      },
      "status": "First Half",
      "statusDetail": "38'",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.9724937739285582,
          "draw": 0.021187228190164664,
          "awayWin": 0.00631899788127718
        },
        "totalGoals": {
          "line": 4.5,
          "over": 0.4654419639179504,
          "under": 0.5345580360820495
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169480"
      }
    },
    {
      "id": "760443",
      "phase": "group-stage",
      "group": "D",
      "kickoffUtc": "2026-06-20T03:00Z",
      "venue": "Levi's Stadium",
      "homeTeamId": "465",
      "awayTeamId": "210",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.46829442804758076,
          "draw": 0.2823539933816296,
          "awayWin": 0.24935157857078974
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.449438202247191,
          "under": 0.550561797752809
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169461"
      }
    },
    {
      "id": "760447",
      "phase": "group-stage",
      "group": "F",
      "kickoffUtc": "2026-06-20T17:00Z",
      "venue": "NRG Stadium",
      "homeTeamId": "449",
      "awayTeamId": "466",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.554633381257352,
          "draw": 0.2354812007145035,
          "awayWin": 0.20988541802814445
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.5776397515527951,
          "under": 0.42236024844720504
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169462"
      }
    },
    {
      "id": "760448",
      "phase": "group-stage",
      "group": "E",
      "kickoffUtc": "2026-06-20T20:00Z",
      "venue": "BMO Field",
      "homeTeamId": "481",
      "awayTeamId": "4789",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.6288539848749273,
          "draw": 0.20421909923149936,
          "awayWin": 0.1669269158935734
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.60431654676259,
          "under": 0.3956834532374101
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169466"
      }
    },
    {
      "id": "760446",
      "phase": "group-stage",
      "group": "E",
      "kickoffUtc": "2026-06-21T00:00Z",
      "venue": "GEHA Field at Arrowhead Stadium",
      "homeTeamId": "209",
      "awayTeamId": "11678",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.8717866836979082,
          "draw": 0.09133003353025705,
          "awayWin": 0.036883282771834586
        },
        "totalGoals": {
          "line": 3.5,
          "over": 0.4140127388535032,
          "under": 0.5859872611464969
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169467"
      }
    },
    {
      "id": "760449",
      "phase": "group-stage",
      "group": "F",
      "kickoffUtc": "2026-06-21T04:00Z",
      "venue": "Estadio BBVA",
      "homeTeamId": "659",
      "awayTeamId": "627",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.1469580254676938,
          "draw": 0.23298223549756328,
          "awayWin": 0.620059739034743
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.4532304725168756,
          "under": 0.5467695274831245
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169468"
      }
    },
    {
      "id": "760453",
      "phase": "group-stage",
      "group": "H",
      "kickoffUtc": "2026-06-21T16:00Z",
      "venue": "Mercedes-Benz Stadium",
      "homeTeamId": "164",
      "awayTeamId": "655",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.8717866836979082,
          "draw": 0.09133003353025705,
          "awayWin": 0.036883282771834586
        },
        "totalGoals": {
          "line": 3.5,
          "over": 0.4400538841490795,
          "under": 0.5599461158509206
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169469"
      }
    },
    {
      "id": "760451",
      "phase": "group-stage",
      "group": "G",
      "kickoffUtc": "2026-06-21T19:00Z",
      "venue": "SoFi Stadium",
      "homeTeamId": "459",
      "awayTeamId": "469",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.6637451902522445,
          "draw": 0.20842240273621204,
          "awayWin": 0.1278324070115434
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.5263157894736842,
          "under": 0.47368421052631576
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169470"
      }
    },
    {
      "id": "760450",
      "phase": "group-stage",
      "group": "H",
      "kickoffUtc": "2026-06-21T22:00Z",
      "venue": "Hard Rock Stadium",
      "homeTeamId": "212",
      "awayTeamId": "2597",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.6527514231499051,
          "draw": 0.2277039848197343,
          "awayWin": 0.11954459203036052
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.42236024844720504,
          "under": 0.5776397515527951
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169471"
      }
    },
    {
      "id": "760452",
      "phase": "group-stage",
      "group": "G",
      "kickoffUtc": "2026-06-22T01:00Z",
      "venue": "BC Place",
      "homeTeamId": "2666",
      "awayTeamId": "2620",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.1743967408335945,
          "draw": 0.22837668442494516,
          "awayWin": 0.5972265747414603
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.4592085979482169,
          "under": 0.5407914020517831
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169472"
      }
    },
    {
      "id": "760456",
      "phase": "group-stage",
      "group": "J",
      "kickoffUtc": "2026-06-22T17:00Z",
      "venue": "AT&T Stadium",
      "homeTeamId": "202",
      "awayTeamId": "474",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.6017699115044248,
          "draw": 0.23893805309734514,
          "awayWin": 0.1592920353982301
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.48427672955974843,
          "under": 0.5157232704402516
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169473"
      }
    },
    {
      "id": "760457",
      "phase": "group-stage",
      "group": "I",
      "kickoffUtc": "2026-06-22T21:00Z",
      "venue": "Lincoln Financial Field",
      "homeTeamId": "478",
      "awayTeamId": "4375",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.886812486727543,
          "draw": 0.08005946060734763,
          "awayWin": 0.03312805266510936
        },
        "totalGoals": {
          "line": 3.5,
          "over": 0.48427672955974843,
          "under": 0.5157232704402516
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169463"
      }
    },
    {
      "id": "760454",
      "phase": "group-stage",
      "group": "I",
      "kickoffUtc": "2026-06-23T00:00Z",
      "venue": "MetLife Stadium",
      "homeTeamId": "464",
      "awayTeamId": "654",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.4051800255077014,
          "draw": 0.272049445698028,
          "awayWin": 0.32277052879427054
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.4891657638136511,
          "under": 0.5108342361863488
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169475"
      }
    },
    {
      "id": "760455",
      "phase": "group-stage",
      "group": "J",
      "kickoffUtc": "2026-06-23T03:00Z",
      "venue": "Levi's Stadium",
      "homeTeamId": "2917",
      "awayTeamId": "624",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.16008316008316006,
          "draw": 0.22869022869022868,
          "awayWin": 0.6112266112266113
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.4947698744769875,
          "under": 0.5052301255230125
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169474"
      }
    },
    {
      "id": "760461",
      "phase": "group-stage",
      "group": "K",
      "kickoffUtc": "2026-06-23T17:00Z",
      "venue": "NRG Stadium",
      "homeTeamId": "482",
      "awayTeamId": "2570",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.7990867579908676,
          "draw": 0.136986301369863,
          "awayWin": 0.0639269406392694
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.6017699115044248,
          "under": 0.39823008849557523
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169476"
      }
    },
    {
      "id": "760458",
      "phase": "group-stage",
      "group": "L",
      "kickoffUtc": "2026-06-23T20:00Z",
      "venue": "Gillette Stadium",
      "homeTeamId": "448",
      "awayTeamId": "4469",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.7841072283389182,
          "draw": 0.14743896601244616,
          "awayWin": 0.06845380564863571
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.5776397515527951,
          "under": 0.42236024844720504
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169477"
      }
    },
    {
      "id": "760460",
      "phase": "group-stage",
      "group": "L",
      "kickoffUtc": "2026-06-23T23:00Z",
      "venue": "BMO Field",
      "homeTeamId": "2659",
      "awayTeamId": "477",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.1469580254676938,
          "draw": 0.23298223549756328,
          "awayWin": 0.620059739034743
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.4891657638136511,
          "under": 0.5108342361863488
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169478"
      }
    },
    {
      "id": "760459",
      "phase": "group-stage",
      "group": "K",
      "kickoffUtc": "2026-06-24T02:00Z",
      "venue": "Estadio Akron",
      "homeTeamId": "208",
      "awayTeamId": "2850",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.6475110795524105,
          "draw": 0.22403956808109496,
          "awayWin": 0.12844935236649446
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.4310344827586207,
          "under": 0.5689655172413793
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34169481"
      }
    },
    {
      "id": "760462",
      "phase": "group-stage",
      "group": "B",
      "kickoffUtc": "2026-06-24T19:00Z",
      "venue": "Lumen Field",
      "homeTeamId": "452",
      "awayTeamId": "4398",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.6576255279211637,
          "draw": 0.19521351478179258,
          "awayWin": 0.14716095729704362
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.5776397515527951,
          "under": 0.42236024844720504
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206865"
      }
    },
    {
      "id": "760463",
      "phase": "group-stage",
      "group": "B",
      "kickoffUtc": "2026-06-24T19:00Z",
      "venue": "BC Place",
      "homeTeamId": "475",
      "awayTeamId": "206",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.3912443305068034,
          "draw": 0.3092092289489253,
          "awayWin": 0.2995464405442714
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.4532304725168756,
          "under": 0.5467695274831245
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206870"
      }
    },
    {
      "id": "760464",
      "phase": "group-stage",
      "group": "C",
      "kickoffUtc": "2026-06-24T22:00Z",
      "venue": "Mercedes-Benz Stadium",
      "homeTeamId": "2869",
      "awayTeamId": "2654",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.7841072283389182,
          "draw": 0.14743896601244616,
          "awayWin": 0.06845380564863571
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.6017699115044248,
          "under": 0.39823008849557523
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206872"
      }
    },
    {
      "id": "760465",
      "phase": "group-stage",
      "group": "C",
      "kickoffUtc": "2026-06-24T22:00Z",
      "venue": "Hard Rock Stadium",
      "homeTeamId": "580",
      "awayTeamId": "205",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.13696948439144158,
          "draw": 0.1743247983163802,
          "awayWin": 0.6887057172921781
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.5367573011077543,
          "under": 0.4632426988922458
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206864"
      }
    },
    {
      "id": "760467",
      "phase": "group-stage",
      "group": "A",
      "kickoffUtc": "2026-06-25T01:00Z",
      "venue": "Estadio Banorte",
      "homeTeamId": "450",
      "awayTeamId": "203",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.2826482357220808,
          "draw": 0.25973081120407426,
          "awayWin": 0.4576209530738451
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.44362292051756,
          "under": 0.5563770794824399
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206873"
      }
    },
    {
      "id": "760466",
      "phase": "group-stage",
      "group": "A",
      "kickoffUtc": "2026-06-25T01:00Z",
      "venue": "Estadio BBVA",
      "homeTeamId": "467",
      "awayTeamId": "451",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.1748821260180026,
          "draw": 0.24046292327475355,
          "awayWin": 0.5846549507072439
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.47368421052631576,
          "under": 0.5263157894736842
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206874"
      }
    },
    {
      "id": "760473",
      "phase": "group-stage",
      "group": "E",
      "kickoffUtc": "2026-06-25T20:00Z",
      "venue": "Lincoln Financial Field",
      "homeTeamId": "11678",
      "awayTeamId": "4789",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.050668543279380716,
          "draw": 0.10696692470091484,
          "awayWin": 0.8423645320197044
        },
        "totalGoals": {
          "line": 3.5,
          "over": 0.4532304725168756,
          "under": 0.5467695274831245
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206875"
      }
    },
    {
      "id": "760468",
      "phase": "group-stage",
      "group": "E",
      "kickoffUtc": "2026-06-25T20:00Z",
      "venue": "MetLife Stadium",
      "homeTeamId": "209",
      "awayTeamId": "481",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.19196865817825662,
          "draw": 0.23996082272282077,
          "awayWin": 0.5680705190989227
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.4947698744769875,
          "under": 0.5052301255230125
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206876"
      }
    },
    {
      "id": "760471",
      "phase": "group-stage",
      "group": "F",
      "kickoffUtc": "2026-06-25T23:00Z",
      "venue": "AT&T Stadium",
      "homeTeamId": "627",
      "awayTeamId": "466",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.44510940714419295,
          "draw": 0.27342435010286137,
          "awayWin": 0.2814662427529456
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.4632426988922458,
          "under": 0.5367573011077543
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206877"
      }
    },
    {
      "id": "760472",
      "phase": "group-stage",
      "group": "F",
      "kickoffUtc": "2026-06-25T23:00Z",
      "venue": "GEHA Field at Arrowhead Stadium",
      "homeTeamId": "659",
      "awayTeamId": "449",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.10090614162658015,
          "draw": 0.1742924264459112,
          "awayWin": 0.7248014319275087
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.574468085106383,
          "under": 0.4255319148936171
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206878"
      }
    },
    {
      "id": "760469",
      "phase": "group-stage",
      "group": "D",
      "kickoffUtc": "2026-06-26T02:00Z",
      "venue": "Levi's Stadium",
      "homeTeamId": "210",
      "awayTeamId": "628",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.4562982005141388,
          "draw": 0.2737789203084833,
          "awayWin": 0.2699228791773779
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.42236024844720504,
          "under": 0.5776397515527951
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206879"
      }
    },
    {
      "id": "760470",
      "phase": "group-stage",
      "group": "D",
      "kickoffUtc": "2026-06-26T02:00Z",
      "venue": "SoFi Stadium",
      "homeTeamId": "465",
      "awayTeamId": "660",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.368280084178305,
          "draw": 0.24870862827625786,
          "awayWin": 0.3830112875454372
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.5263157894736842,
          "under": 0.47368421052631576
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206880"
      }
    },
    {
      "id": "760475",
      "phase": "group-stage",
      "group": "I",
      "kickoffUtc": "2026-06-26T19:00Z",
      "venue": "Gillette Stadium",
      "homeTeamId": "464",
      "awayTeamId": "478",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.2226450999048525,
          "draw": 0.24548049476688866,
          "awayWin": 0.5318744053282588
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.5367573011077543,
          "under": 0.4632426988922458
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206882"
      }
    },
    {
      "id": "760474",
      "phase": "group-stage",
      "group": "I",
      "kickoffUtc": "2026-06-26T19:00Z",
      "venue": "BMO Field",
      "homeTeamId": "654",
      "awayTeamId": "4375",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.7378048780487805,
          "draw": 0.17479674796747968,
          "awayWin": 0.08739837398373984
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.5157232704402516,
          "under": 0.48427672955974843
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206881"
      }
    },
    {
      "id": "760478",
      "phase": "group-stage",
      "group": "H",
      "kickoffUtc": "2026-06-27T00:00Z",
      "venue": "NRG Stadium",
      "homeTeamId": "2597",
      "awayTeamId": "655",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.3473227206946454,
          "draw": 0.25470332850940663,
          "awayWin": 0.3979739507959479
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.4632426988922458,
          "under": 0.5367573011077543
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206884"
      }
    },
    {
      "id": "760479",
      "phase": "group-stage",
      "group": "H",
      "kickoffUtc": "2026-06-27T00:00Z",
      "venue": "Estadio Akron",
      "homeTeamId": "212",
      "awayTeamId": "164",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.15898034637088926,
          "draw": 0.22183304144775245,
          "awayWin": 0.6191866121813582
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.5157232704402516,
          "under": 0.48427672955974843
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206883"
      }
    },
    {
      "id": "760476",
      "phase": "group-stage",
      "group": "G",
      "kickoffUtc": "2026-06-27T03:00Z",
      "venue": "Lumen Field",
      "homeTeamId": "2620",
      "awayTeamId": "469",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.45627376425855515,
          "draw": 0.30418250950570347,
          "awayWin": 0.2395437262357415
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.38604808669150015,
          "under": 0.6139519133084999
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206885"
      }
    },
    {
      "id": "760477",
      "phase": "group-stage",
      "group": "G",
      "kickoffUtc": "2026-06-27T03:00Z",
      "venue": "BC Place",
      "homeTeamId": "2666",
      "awayTeamId": "459",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.07394366197183098,
          "draw": 0.14788732394366197,
          "awayWin": 0.778169014084507
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.5806451612903226,
          "under": 0.4193548387096774
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206886"
      }
    },
    {
      "id": "760480",
      "phase": "group-stage",
      "group": "L",
      "kickoffUtc": "2026-06-27T21:00Z",
      "venue": "Lincoln Financial Field",
      "homeTeamId": "477",
      "awayTeamId": "4469",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.6052974381241859,
          "draw": 0.23447676943117673,
          "awayWin": 0.16022579244463742
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.4632426988922458,
          "under": 0.5367573011077543
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206887"
      }
    },
    {
      "id": "760485",
      "phase": "group-stage",
      "group": "L",
      "kickoffUtc": "2026-06-27T21:00Z",
      "venue": "MetLife Stadium",
      "homeTeamId": "2659",
      "awayTeamId": "448",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.0909090909090909,
          "draw": 0.13636363636363635,
          "awayWin": 0.7727272727272727
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.6017699115044248,
          "under": 0.39823008849557523
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206866"
      }
    },
    {
      "id": "760481",
      "phase": "group-stage",
      "group": "K",
      "kickoffUtc": "2026-06-27T23:30Z",
      "venue": "Hard Rock Stadium",
      "homeTeamId": "208",
      "awayTeamId": "482",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.26448362720403024,
          "draw": 0.27581863979848864,
          "awayWin": 0.4596977329974811
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.4632426988922458,
          "under": 0.5367573011077543
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206871"
      }
    },
    {
      "id": "760482",
      "phase": "group-stage",
      "group": "K",
      "kickoffUtc": "2026-06-27T23:30Z",
      "venue": "Mercedes-Benz Stadium",
      "homeTeamId": "2850",
      "awayTeamId": "2570",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.4559985302223039,
          "draw": 0.26235531875803786,
          "awayWin": 0.2816461510196583
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.4532304725168756,
          "under": 0.5467695274831245
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206867"
      }
    },
    {
      "id": "760484",
      "phase": "group-stage",
      "group": "J",
      "kickoffUtc": "2026-06-28T02:00Z",
      "venue": "GEHA Field at Arrowhead Stadium",
      "homeTeamId": "624",
      "awayTeamId": "474",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.31447041272998505,
          "draw": 0.30939830929885626,
          "awayWin": 0.37613127797115864
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.449438202247191,
          "under": 0.550561797752809
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206868"
      }
    },
    {
      "id": "760483",
      "phase": "group-stage",
      "group": "J",
      "kickoffUtc": "2026-06-28T02:00Z",
      "venue": "AT&T Stadium",
      "homeTeamId": "2917",
      "awayTeamId": "202",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false,
      "odds": {
        "provider": "DraftKings via ESPN",
        "fetchedAt": "2026-06-20T01:55:54.370Z",
        "moneyline": {
          "homeWin": 0.06836827711941658,
          "draw": 0.1276207839562443,
          "awayWin": 0.8040109389243391
        },
        "totalGoals": {
          "line": 2.5,
          "over": 0.6017699115044248,
          "under": 0.39823008849557523
        },
        "confidence": "high",
        "sourceUrl": "https://sportsbook.draftkings.com/gateway?s=__s__&wpcid=__wpcid__&wpsrc=413&wpcn=ESPN&wpscn=Widget&wpcrn=BetSlipDeepLink&wpscid=__wpscid__&wpcrid=xx&preurl=https%3A%2F%2Fsportsbook.draftkings.com%2Fevent%2F34206869"
      }
    },
    {
      "id": "760486",
      "phase": "round-of-32",
      "kickoffUtc": "2026-06-28T19:00Z",
      "venue": "SoFi Stadium",
      "homeTeamId": "5926",
      "awayTeamId": "5924",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760487",
      "phase": "round-of-32",
      "kickoffUtc": "2026-06-29T17:00Z",
      "venue": "NRG Stadium",
      "homeTeamId": "5927",
      "awayTeamId": "5934",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760489",
      "phase": "round-of-32",
      "kickoffUtc": "2026-06-29T20:30Z",
      "venue": "Gillette Stadium",
      "homeTeamId": "5931",
      "awayTeamId": "131541",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760488",
      "phase": "round-of-32",
      "kickoffUtc": "2026-06-30T01:00Z",
      "venue": "Estadio BBVA",
      "homeTeamId": "5933",
      "awayTeamId": "5930",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760490",
      "phase": "round-of-32",
      "kickoffUtc": "2026-06-30T17:00Z",
      "venue": "AT&T Stadium",
      "homeTeamId": "5932",
      "awayTeamId": "131501",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760492",
      "phase": "round-of-32",
      "kickoffUtc": "2026-06-30T21:00Z",
      "venue": "MetLife Stadium",
      "homeTeamId": "131505",
      "awayTeamId": "131544",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760491",
      "phase": "round-of-32",
      "kickoffUtc": "2026-07-01T01:00Z",
      "venue": "Estadio Banorte",
      "homeTeamId": "203",
      "awayTeamId": "131545",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760495",
      "phase": "round-of-32",
      "kickoffUtc": "2026-07-01T16:00Z",
      "venue": "Mercedes-Benz Stadium",
      "homeTeamId": "131508",
      "awayTeamId": "131548",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760493",
      "phase": "round-of-32",
      "kickoffUtc": "2026-07-01T20:00Z",
      "venue": "Lumen Field",
      "homeTeamId": "5935",
      "awayTeamId": "131542",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760494",
      "phase": "round-of-32",
      "kickoffUtc": "2026-07-02T00:00Z",
      "venue": "Levi's Stadium",
      "homeTeamId": "5929",
      "awayTeamId": "131543",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760497",
      "phase": "round-of-32",
      "kickoffUtc": "2026-07-02T19:00Z",
      "venue": "SoFi Stadium",
      "homeTeamId": "5937",
      "awayTeamId": "131502",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760496",
      "phase": "round-of-32",
      "kickoffUtc": "2026-07-02T23:00Z",
      "venue": "BMO Field",
      "homeTeamId": "131503",
      "awayTeamId": "131504",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760498",
      "phase": "round-of-32",
      "kickoffUtc": "2026-07-03T03:00Z",
      "venue": "BC Place",
      "homeTeamId": "5925",
      "awayTeamId": "131547",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760499",
      "phase": "round-of-32",
      "kickoffUtc": "2026-07-03T18:00Z",
      "venue": "AT&T Stadium",
      "homeTeamId": "5928",
      "awayTeamId": "5936",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760500",
      "phase": "round-of-32",
      "kickoffUtc": "2026-07-03T22:00Z",
      "venue": "Hard Rock Stadium",
      "homeTeamId": "131506",
      "awayTeamId": "5938",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760501",
      "phase": "round-of-32",
      "kickoffUtc": "2026-07-04T01:30Z",
      "venue": "GEHA Field at Arrowhead Stadium",
      "homeTeamId": "131507",
      "awayTeamId": "131546",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760502",
      "phase": "round-of-16",
      "kickoffUtc": "2026-07-04T17:00Z",
      "venue": "NRG Stadium",
      "homeTeamId": "131525",
      "awayTeamId": "131527",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760503",
      "phase": "round-of-16",
      "kickoffUtc": "2026-07-04T21:00Z",
      "venue": "Lincoln Financial Field",
      "homeTeamId": "131526",
      "awayTeamId": "131529",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760504",
      "phase": "round-of-16",
      "kickoffUtc": "2026-07-05T20:00Z",
      "venue": "MetLife Stadium",
      "homeTeamId": "131528",
      "awayTeamId": "131530",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760505",
      "phase": "round-of-16",
      "kickoffUtc": "2026-07-06T00:00Z",
      "venue": "Estadio Banorte",
      "homeTeamId": "131531",
      "awayTeamId": "131532",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760506",
      "phase": "round-of-16",
      "kickoffUtc": "2026-07-06T19:00Z",
      "venue": "AT&T Stadium",
      "homeTeamId": "131535",
      "awayTeamId": "131536",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760507",
      "phase": "round-of-16",
      "kickoffUtc": "2026-07-07T00:00Z",
      "venue": "Lumen Field",
      "homeTeamId": "131533",
      "awayTeamId": "131534",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760509",
      "phase": "round-of-16",
      "kickoffUtc": "2026-07-07T16:00Z",
      "venue": "Mercedes-Benz Stadium",
      "homeTeamId": "131538",
      "awayTeamId": "131540",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760508",
      "phase": "round-of-16",
      "kickoffUtc": "2026-07-07T20:00Z",
      "venue": "BC Place",
      "homeTeamId": "131537",
      "awayTeamId": "131539",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760510",
      "phase": "quarterfinals",
      "kickoffUtc": "2026-07-09T20:00Z",
      "venue": "Gillette Stadium",
      "homeTeamId": "19282",
      "awayTeamId": "19283",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760511",
      "phase": "quarterfinals",
      "kickoffUtc": "2026-07-10T19:00Z",
      "venue": "SoFi Stadium",
      "homeTeamId": "19278",
      "awayTeamId": "19279",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760512",
      "phase": "quarterfinals",
      "kickoffUtc": "2026-07-11T21:00Z",
      "venue": "Hard Rock Stadium",
      "homeTeamId": "19284",
      "awayTeamId": "19285",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760513",
      "phase": "quarterfinals",
      "kickoffUtc": "2026-07-12T01:00Z",
      "venue": "GEHA Field at Arrowhead Stadium",
      "homeTeamId": "19280",
      "awayTeamId": "19281",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760514",
      "phase": "semifinals",
      "kickoffUtc": "2026-07-14T19:00Z",
      "venue": "AT&T Stadium",
      "homeTeamId": "17631",
      "awayTeamId": "17629",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760515",
      "phase": "semifinals",
      "kickoffUtc": "2026-07-15T19:00Z",
      "venue": "Mercedes-Benz Stadium",
      "homeTeamId": "17630",
      "awayTeamId": "17632",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760516",
      "phase": "3rd-place-match",
      "kickoffUtc": "2026-07-18T21:00Z",
      "venue": "Hard Rock Stadium",
      "homeTeamId": "5958",
      "awayTeamId": "5959",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    },
    {
      "id": "760517",
      "phase": "final",
      "kickoffUtc": "2026-07-19T19:00Z",
      "venue": "MetLife Stadium",
      "homeTeamId": "5960",
      "awayTeamId": "5961",
      "apiScore": null,
      "status": "Scheduled",
      "statusDetail": "Scheduled",
      "completed": false
    }
  ]
} as const;
